(($) ->
  $ ->
    $('.button-collapse').sideNav()
    $('.parallax').parallax()
    return
  # end of document ready
  return
) jQuery
# end of jQuery name space

# ---
# generated by js2coffee 2.1.0